### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by BoLaMN** [taoyuan/loopback-aggregation-mixin#1]
I see this code is very similar to the mixin i released. 

I believe in the open source community, 
please give credit where credit is due. 

Regards

**Comment by taoyuan** [comment]
You are right. I'm sorry about that. 

The README is auto generated, and I'm going to write a simple README including creds.

**Comment by taoyuan** [comment]
I have updated a simple README including creds. Thanks your contribution.

**Comment by BoLaMN** [comment]
👍
